### PR TITLE
add alias command for makemessages and used parameters

### PR DESCRIPTION
**Pull request by janno42**

### CODE REVIEW

**Review by He3lixxx — APPROVED** [review]
You could add a test, but, like, it really doesn't make a difference I think.

**Comment by karyon** [comment]
If django changed e.g. the command's parameters and this custom one would start failing, a test that just checks for the return value might help us notice it sooner than on the next release. Then again, django's command didn't change for years now.

On November 8, 2021 10:27:03 PM GMT+01:00, Richard Ebeling ***@***.***> wrote:
***@***.*** approved this pull request.

**Review by niklasmohrin — APPROVED** [review]

**Comment by janno42** [comment]
the test doesn't seem to be the best idea in the current implementation

**Comment by janno42** [comment]
i removed the test again, will be merged without it

**Pull request merged**
