### PR TITLE
Add keyboard shortcut for toggling flag state of textanswer

### LINKED ISSUE #1974: Hotkey for flagging Textanswers
When reviewing Textanswers in quick view, there are hotkeys for various operations. The newly implemented flagging (#1815) does not yet have a hotkey. The keys `F` and `D` should be added to set or remove a flag and should be added to the hotkey overview.

### PR DESCRIPTION
**Pull request by niklasmohrin**
Closes #1974

### CODE REVIEW

**Review by He3lixxx — APPROVED** [review]

**Comment by niklasmohrin** [comment]
Any opinion on clicking on `input` vs `label`? Users click on the label, but clicking the input should be just as fine, unless we ever move the input under another clickable thing, but that would be insane. Not impossible though. Any more thoughts?

**Comment by He3lixxx** [comment]
> Any opinion on clicking on `input` vs `label`? Users click on the label, but clicking the input should be just as fine, unless we ever move the input under another clickable thing, but that would be insane. Not impossible though. Any more thoughts?

I'm fine with both, I think both are equally likely to break. If we want to prevent that, we'd need to add a test.

**Comment by niklasmohrin** [comment]
Pinging #1854

**Review by janno42 — APPROVED** [review]
✔️ Meets requirements
✔️ UI functionality checked

**Pull request merged**
