### PR TITLE
Update to psycopg3

### LINKED ISSUE #2118: Upgrade to psycopg3
In https://github.com/e-valuation/EvaP/pull/2084, we wanted to update our psycopg dependency to `psycopg[binary]==3.1.14`. The tests failed due to [a bug in django](https://code.djangoproject.com/ticket/35028). They have fixed the bug since then, so with django 5.1, we should be able to upgrade.

### PR DESCRIPTION
**Pull request by richardebeling**
Fixes #2118

### CODE REVIEW

**Review by niklasmohrin — APPROVED** [review]

**Review by Kakadus — APPROVED** [review]

**Comment by niklasmohrin** [comment]
@ybrnr Can you try to run the following and post the output, if any errors occur?
```
nix develop github:niklasmohrin/evap/psycopg-non-binary
./manage.py test --keepdb --parallel
```

**Comment by ybrnr** [comment]
@niklasmohrin it ran without any errors

**Comment by niklasmohrin** [comment]
Ah, sorry, incomplete instructions. There must also be a `nix run .#services-full` running, from the output I assume it wasn't (was it?)

**Comment by ybrnr** [comment]
No, it wasn't. But that is the Problem. When trying `nix run .#services-full` I get:
`error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'process-compose'
         whose name attribute is located at /nix/store/ia1zpg1s63v6b3vin3n7bxxjgcs51s2r-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'text' of derivation 'process-compose'
         at /nix/store/ia1zpg1s63v6b3vin3n7bxxjgcs51s2r-source/pkgs/build-support/trivial-builders/default.nix:94:17:
           93|       ({
           94|         inherit text executable checkPhase allowSubstitutes preferLocalBuild;
             |                 ^
           95|         passAsFile = [ "text" ]

       … while evaluating the option `outputs.settingsFile':

       … while evaluating definitions from `/nix/store/abzvbm33gi4iisx8fijq127v2l5xmh34-source/nix/process-compose/settings':

       … while evaluating the option `settings.processes.init-django.command':

       … while calculating requiredPythonModules for python3.10-psycopg-3.2.3:

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: Missing suitable source/wheel file entry for psycopg-binary`

**Comment by niklasmohrin** [comment]
Ah, right. Okay, so what about `nix run github:niklasmohrin/evap/psycopg-non-binary#services-full` together with `nix develop github:niklasmohrin/evap/psycopg-non-binary` (so all `nix` commands point to my repository)? Does running the tests work then?

**Comment by ybrnr** [comment]
Well the services work but most of the tests fail:

Its a lot of text so I shortened it but the error message is (as far as I could tell) the same for every test

```
Creating test database for alias 'default'...
Found 594 test(s).
System check identified no issues (0 silenced).
...E..EEEEEEEEEEEEEEEEEEE.....EEE.EEEE.................................EE.........................................................................EE.EEEEEEEEEEEEEEEEEEEEEEEEEEEE...................................EE.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE..EEEEEEEEEEEEEEEEEEE........................................................................................................EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EEEEE.EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_form_ordering (evap.contributor.tests.test_forms.ContributionFormsetWebTests)
Asserts that the contribution formset is correctly sorted,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yannik/Dev/EvaP/evap/contributor/tests/test_forms.py", line 198, in test_form_ordering
    response = str(self.app.post(f"/contributor/evaluation/{evaluation.pk}/edit", params=data, user=user1))
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django_webtest/__init__.py", line 151, in post
    return super(DjangoTestApp, self).post(url, *args, **kwargs)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/webtest/app.py", line 372, in post
    return self._gen_request('POST', url, params=params, headers=headers,
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/webtest/app.py", line 756, in _gen_request
    return self.do_request(req, status=status,
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django_webtest/__init__.py", line 100, in do_request
    response = super(DjangoTestApp, self).do_request(req, status,
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/webtest/app.py", line 627, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/webob/request.py", line 1309, in send
    status, headers, app_iter, exc_info = self.call_application(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/webtest/lint.py", line 196, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django_webtest/middleware.py", line 61, in process_request
    auth.login(request, user)
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 112, in login
    session_auth_hash = user.get_session_auth_hash()
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 136, in get_session_auth_hash
    return self._get_session_auth_hash()
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 144, in _get_session_auth_hash
    return salted_hmac(
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/utils/crypto.py", line 28, in salted_hmac
    secret = settings.SECRET_KEY
  File "/nix/store/3k2mcav8dnp1n3g9g9jx9148a8md4fl1-python3-3.10.14-env/lib/python3.10/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

======================================================================

----------------------------------------------------------------------
Ran 594 tests in 12.576s

FAILED (errors=332)
Destroying test database for alias 'default'...
```

**Comment by niklasmohrin** [comment]
Okay, that seems like a separate problem though, I suspect it's similar to what we fixed the last time

**Comment by niklasmohrin** [comment]
@ybrnr Can you run `cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32` once in your normal shell, and then a second time inside a `nix shell nixpkgs#coreutils`?

**Pull request merged**
